#!/usr/bin/env php
<?php
namespace Mars\Bin;

use Mars\App;

require __DIR__ . '/vendor/autoload.php';

try {
    $app = App::obj();
    if (!$app->is_cli) {
        die("bin/mars must be run as a CLI application\n");
    }

    $app->bin = new Bin($app);
    $app->bin->run();
} catch (\Exception $e) {
    $app->cli->error("Error: " . $e->getMessage());
}