#!/usr/bin/env php
<?php
namespace Mars\Bin;

use Mars\App;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/webdev1404/mars-bin/functions.php';

$app = App::obj();
if (!$app->is_cli) {
    die("bin/mars must be run as a CLI application\n");
}

try {
    $action = get_action();
    $command = get_command();

    $available_actions = get_available_actions();
    if (!isset($available_actions[$action])) {
        throw new \Exception("Action {$action} not found");
    }

    $obj = $available_actions[$action];
    $obj->execute($command);
} catch (\Exception $e) {
    $app->cli->error("Error: " . $e->getMessage());
}