#!/usr/bin/env php
<?php
namespace Mars\Bin;

use Mars\App;

require __DIR__ . '/vendor/autoload.php';

$app = App::obj();
if (!$app->is_cli) {
    die("bin/mars must be run as a CLI application\n");
}

try {
    $app->bin = new Bin($app);
    if (!$app->bin->exists()) {
        throw new \Exception("Action {$app->bin->action} not found");
    }

    $obj = $app->bin->get();
    $obj->execute($app->bin->command);
} catch (\Exception $e) {
    $app->cli->error("Error: " . $e->getMessage());
}